In [1]:
import numpy as np

In [2]:
L = np.random.random(100)

In [3]:
L

array([0.6308852 , 0.31311801, 0.49113233, 0.01606705, 0.64592246,
       0.28197231, 0.75150017, 0.70802648, 0.37451557, 0.88401148,
       0.9210089 , 0.19380547, 0.77209961, 0.70048662, 0.94950381,
       0.86940104, 0.15189247, 0.82006639, 0.44691576, 0.59205713,
       0.44537063, 0.01712398, 0.84334624, 0.05421644, 0.11888391,
       0.76527164, 0.82137644, 0.4494521 , 0.30494561, 0.08718755,
       0.20466978, 0.82605239, 0.2859134 , 0.23172423, 0.01303262,
       0.27647154, 0.76656965, 0.25110593, 0.48982554, 0.23719977,
       0.80081006, 0.34358083, 0.85950503, 0.94120428, 0.17297496,
       0.33233192, 0.96454189, 0.02309114, 0.08598476, 0.28023344,
       0.52117983, 0.26139052, 0.99390746, 0.27009964, 0.21173846,
       0.30956934, 0.21395755, 0.9221491 , 0.19007217, 0.36422699,
       0.34899078, 0.35730445, 0.51210192, 0.16662754, 0.37675926,
       0.58199192, 0.16414022, 0.4782824 , 0.5224641 , 0.90041694,
       0.49389936, 0.30111913, 0.19898479, 0.57637078, 0.04548

In [4]:
sum(L)

45.73545691377853

In [5]:
np.sum(L)

45.73545691377852

In [6]:
np.min(L)

0.013032623328541604

In [7]:
np.max(L)

0.9939074560215214

In [8]:
X = np.arange(16).reshape(4,-1)

In [9]:
X

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [10]:
np.sum(X)

120

In [11]:
np.sum(X, axis = 0)

array([24, 28, 32, 36])

In [12]:
np.sum(X, axis = 1)

array([ 6, 22, 38, 54])

In [13]:
np.prod(X)

0

In [14]:
np.prod(X+1)

2004189184

In [15]:
np.mean(X)

7.5

In [16]:
np.median(X)

7.5

In [17]:
v = np.array([1,1,2,2,100])

In [18]:
np.mean(v)

21.2

In [19]:
np.median(v)

2.0

In [20]:
np.percentile(v,50)

2.0

In [21]:
np.percentile(v, 100)

100.0

####  percentile ==> 百分位点

In [22]:
np.var(v)

1552.56

In [23]:
np.std(v)

39.40253798932246

In [24]:
x = np.random.normal(0 ,4,10000)

In [25]:
np.mean(x)

-0.02132893119870155

In [26]:
np.var(x)

16.061508737197048

In [27]:
np.std(x)

4.007681217012781

## 索引

In [28]:
np.min(x)

-17.337529023689157

In [29]:
np.argmin(x)

3827

In [30]:
x[857]

-3.6504267468308282

In [31]:
np.max(x)

15.356520027066217

In [32]:
np.argmax(x)

1250

In [33]:
x[4571]

-0.15665629231292452

## 排序和使用索引

In [36]:
x = np.arange(16)

In [37]:
x

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [38]:
np.random.shuffle(x)
x

array([ 8, 12,  5, 13, 10, 11,  0,  2,  1,  4,  3, 14, 15,  7,  9,  6])

In [39]:
np.sort(x)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [40]:
x

array([ 8, 12,  5, 13, 10, 11,  0,  2,  1,  4,  3, 14, 15,  7,  9,  6])

In [42]:
x.sort()

In [43]:
x

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [44]:
X = np.random.randint(10, size=(4,4))
X

array([[3, 4, 3, 9],
       [6, 1, 4, 1],
       [8, 2, 1, 4],
       [7, 6, 0, 9]])

In [45]:
np.sort(X , axis= 1)

array([[3, 3, 4, 9],
       [1, 1, 4, 6],
       [1, 2, 4, 8],
       [0, 6, 7, 9]])

In [46]:
np.sort(X , axis = 0)

array([[3, 1, 0, 1],
       [6, 2, 1, 4],
       [7, 4, 3, 9],
       [8, 6, 4, 9]])

In [47]:
x

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [48]:
np.random.shuffle(x)

In [49]:
x

array([10, 11, 14,  3,  2, 15,  4, 12, 13,  0,  9,  5,  8,  1,  7,  6])

In [50]:
np.argsort(x)

array([ 9, 13,  4,  3,  6, 11, 15, 14, 12, 10,  0,  1,  7,  8,  2,  5],
      dtype=int64)

In [59]:
np.partition(x, 4)

array([ 1,  0,  2,  3,  4,  7,  6,  8,  5,  9, 10, 13, 11, 15, 14, 12])

In [58]:
 np.argpartition(x, 4)

array([13,  9,  4,  3,  6, 14, 15, 12, 11, 10,  0,  8,  1,  5,  2,  7],
      dtype=int64)

In [53]:
X

array([[3, 4, 3, 9],
       [6, 1, 4, 1],
       [8, 2, 1, 4],
       [7, 6, 0, 9]])

In [54]:
np.argsort(X , axis = 1)

array([[0, 2, 1, 3],
       [1, 3, 2, 0],
       [2, 1, 3, 0],
       [2, 1, 0, 3]], dtype=int64)

In [61]:
np.partition(X, 2 ,axis = 1)

array([[3, 3, 4, 9],
       [1, 1, 4, 6],
       [1, 2, 4, 8],
       [0, 6, 7, 9]])

In [60]:
np.argpartition(X, 2 ,axis = 1)

array([[0, 2, 1, 3],
       [1, 3, 2, 0],
       [2, 1, 3, 0],
       [2, 1, 0, 3]], dtype=int64)