In [2]:
import numpy as np

In [3]:
x = np.arange(10)

In [4]:
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [5]:
X  = np.arange(15).reshape((3,5))

In [6]:
X

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

# 基本属性

In [7]:
x.ndim

1

In [8]:
X.ndim

2

In [9]:
x.shape

(10,)

In [10]:
X.shape

(3, 5)

In [11]:
x.size

10

In [12]:
X.size

15

# numpy.array的数据访问

In [13]:
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [14]:
x[0]

0

In [15]:
x[-1]

9

In [16]:
X

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [17]:
X[0][0]

0

* 不建议这样访问 [ ][ ]

In [18]:
X[2,2]

12

In [19]:
x[0:5]

array([0, 1, 2, 3, 4])

In [21]:
x[:8]

array([0, 1, 2, 3, 4, 5, 6, 7])

In [22]:
x[::2]

array([0, 2, 4, 6, 8])

In [23]:
x[::-1]

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

In [24]:
X

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [25]:
X[:2,:3]

array([[0, 1, 2],
       [5, 6, 7]])

In [26]:
X[:2][:3]

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

### 请务必使用 [ a, b]

In [27]:
X[:2, ::2]

array([[0, 2, 4],
       [5, 7, 9]])

In [28]:
X[::-1,::-1]

array([[14, 13, 12, 11, 10],
       [ 9,  8,  7,  6,  5],
       [ 4,  3,  2,  1,  0]])

In [29]:
X[0]

array([0, 1, 2, 3, 4])

In [30]:
X[0, :]

array([0, 1, 2, 3, 4])

In [31]:
X[0, :].ndim

1

In [32]:
X[:, 0]

array([ 0,  5, 10])

In [33]:
X[:, 0].ndim

1

In [34]:
subX = X[:2, :3]

In [35]:
subX

array([[0, 1, 2],
       [5, 6, 7]])

In [36]:
subX[0, 0] = 100

In [37]:
subX

array([[100,   1,   2],
       [  5,   6,   7]])

In [39]:
X

array([[100,   1,   2,   3,   4],
       [  5,   6,   7,   8,   9],
       [ 10,  11,  12,  13,  14]])

In [40]:
X[0, 0] = 0

In [41]:
X

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [42]:
subX

array([[0, 1, 2],
       [5, 6, 7]])

### numpy的切片相当于一个引用

In [46]:
subX = X[:2, :3].copy()

In [47]:
subX

array([[0, 1, 2],
       [5, 6, 7]])

In [48]:
subX[0, 0] = 100

In [49]:
subX

array([[100,   1,   2],
       [  5,   6,   7]])

In [50]:
X

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

# reshape

In [51]:
x.shape

(10,)

In [52]:
x.ndim 

1

In [53]:
x.reshape((2, 5))

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [54]:
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [55]:
A = x.reshape((2, 5))
A

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [56]:
B = x.reshape(1, 10)

In [57]:
B

array([[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]])

In [58]:
B.ndim

2

In [59]:
x.shape

(10,)

In [60]:
B.shape

(1, 10)

In [61]:
x.reshape((10, -1))

array([[0],
       [1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [8],
       [9]])

In [62]:
x.reshape((-1, 10))

array([[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]])

In [63]:
x.reshape((2, -1))

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

# 合并与分割

## 合并

In [64]:
x = np.array([1,2,3])
y = np.array([4,5,6])
x
y

array([4, 5, 6])

In [65]:
x

array([1, 2, 3])

In [66]:
y

array([4, 5, 6])

In [67]:
np.concatenate([x,y])

array([1, 2, 3, 4, 5, 6])

In [68]:
z = np.array([7,8,9])

In [69]:
z

array([7, 8, 9])

In [70]:
np.concatenate([x,y,z])

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [71]:
A = np.arange(1,7).reshape(2,3)

In [72]:
A

array([[1, 2, 3],
       [4, 5, 6]])

In [73]:
np.concatenate([A,A])

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6]])

In [74]:
np.concatenate([A,A],axis=1)

array([[1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6]])

### axis默认值为0 沿着行的方向拼接 (行增长)
### 按照第1行、第2行、第3行......第n行这样拼接

### axis = 1 沿着列的方向拼接(列增长)
### 同理按照第1列、第2列、第3列......第n列这样拼接

In [75]:
np.concatenate([A,z])

ValueError: all the input arrays must have same number of dimensions

In [76]:
Z = z.reshape(1,-1)

In [77]:
Z

array([[7, 8, 9]])

In [78]:
np.concatenate([A,Z])

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [79]:
A

array([[1, 2, 3],
       [4, 5, 6]])

In [80]:
A2 = np.concatenate([A,Z])

In [81]:
A2

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [82]:
np.vstack([A,z])

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [83]:
B = np.full((2,2), 100)

In [84]:
B

array([[100, 100],
       [100, 100]])

In [85]:
np.hstack([A,B])

array([[  1,   2,   3, 100, 100],
       [  4,   5,   6, 100, 100]])

## 分割

In [86]:
x = np.arange(10)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [90]:
x1, x2, x3 = np.split(x, [3, 7])

In [91]:
x1

array([0, 1, 2])

In [92]:
x2

array([3, 4, 5, 6])

In [93]:
x3

array([7, 8, 9])

In [96]:
x1 , x2 = np.split(x, [5])

In [97]:
x1

array([0, 1, 2, 3, 4])

In [98]:
x2

array([5, 6, 7, 8, 9])

In [99]:
A = np.arange(16).reshape((4, 4))

In [100]:
A

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [101]:
A1, A2 = np.split(A, [2])

In [102]:
A1

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [103]:
A2

array([[ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [104]:
A1, A2 = np.split(A, [2], axis= 1)

In [105]:
A1

array([[ 0,  1],
       [ 4,  5],
       [ 8,  9],
       [12, 13]])

In [106]:
A2

array([[ 2,  3],
       [ 6,  7],
       [10, 11],
       [14, 15]])

In [107]:
upper, lower = np.vsplit(A, [2])

In [108]:
upper

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

In [109]:
lower

array([[ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [110]:
left, right = np.hsplit(A, [2])

In [111]:
left

array([[ 0,  1],
       [ 4,  5],
       [ 8,  9],
       [12, 13]])

In [112]:
right

array([[ 2,  3],
       [ 6,  7],
       [10, 11],
       [14, 15]])

In [113]:
data = np.arange(16).reshape((4,4))

In [114]:
data

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [118]:
X, Y = np.hsplit(data, [3])

In [119]:
X

array([[ 0,  1,  2],
       [ 4,  5,  6],
       [ 8,  9, 10],
       [12, 13, 14]])

In [120]:
Y

array([[ 3],
       [ 7],
       [11],
       [15]])

In [121]:
Y.shape

(4, 1)

In [127]:
y = Y[:,0]

In [128]:
y

array([ 3,  7, 11, 15])

In [129]:
y.shape

(4,)

In [130]:
y2 = Y.reshape(1,-1)

In [131]:
y2

array([[ 3,  7, 11, 15]])

In [132]:
y2.shape

(1, 4)