# 实现多元线性回归

In [1]:
import numpy as np
import matplotlib.pyplot as plt
from sklearn import datasets

In [2]:
boston = datasets.load_boston()

X = boston.data
y = boston.target

X = X[y < 50.0]
y = y[y < 50.0]

In [3]:
X.shape

(490, 13)

In [4]:
import sys
sys.path.append("C:\\Users\\liqiang\\Documents\\pythonWK\\Machine Learning")

In [5]:
from playML.model_selection import train_test_split

In [6]:
X_train, X_test, y_train, y_test = train_test_split(X, y, seed=666)

In [7]:
from playML.LinearRegression import LinearRegression

In [8]:
reg = LinearRegression()
reg.fit_normal(X_train, y_train)

LinearRegression()

In [9]:
reg.coef_

array([-1.18919477e-01,  3.63991462e-02, -3.56494193e-02,  5.66737830e-02,
       -1.16195486e+01,  3.42022185e+00, -2.31470282e-02, -1.19509560e+00,
        2.59339091e-01, -1.40112724e-02, -8.36521175e-01,  7.92283639e-03,
       -3.81966137e-01])

In [10]:
reg.intercept_

34.161435496213905

In [11]:
reg.score(X_test, y_test)

0.8129802602658359

In [12]:
reg.predict(X_test[:1,:])

array([18.08047724])

## X必须使用2维的

In [13]:
X_test[1].shape

(13,)

In [14]:
X_test[1].ndim

1

In [15]:
X_test[1]

array([2.1409e-01, 2.2000e+01, 5.8600e+00, 0.0000e+00, 4.3100e-01,
       6.4380e+00, 8.9000e+00, 7.3967e+00, 7.0000e+00, 3.3000e+02,
       1.9100e+01, 3.7707e+02, 3.5900e+00])

In [16]:
X_test[:1,:]

array([[3.2543e-01, 0.0000e+00, 2.1890e+01, 0.0000e+00, 6.2400e-01,
        6.4310e+00, 9.8800e+01, 1.8125e+00, 4.0000e+00, 4.3700e+02,
        2.1200e+01, 3.9690e+02, 1.5390e+01]])

In [17]:
X_test[:1,:].ndim

2